// streetsNames1030

const BCE_TypeEntity = [
    "non renseigné",
    "Enterprise",
    "Establishment",
    "Branch",
]

const BCE_TypeEnterprise = [
    "Personne morale",
    "Personne physique",
]

const BCE_JuridicalForm = [
    "Association internationale sans but lucratif",
    "Association sans but lucratif",
    "Autre service fédéral",
    "Entité étrangère",
    "Société à responsabilité limitée",
    "Société à responsabilité limitée de droit public",
    "Société anonyme",
    "Société anonyme de droit public",
    "Société coopérative",
    "Société coopérative (ancien statut)",
    "Société coopérative à responsabilité illimitée",
    "Société coopérative à responsabilité limitée",
    "Société en commandite",
    "Société en commandite simple",
    "Société en nom collectif",
    "Société ou association sans personnalité juridique",
    "Société privée à responsabilité limitée",
    "Union professionnelle",
    "Unité TVA"
]

const BCE_SecEconomique = [
    "non renseigné",
    //"Activités De Service Administratif Et De Soutien",
    //"Activités Financières Et D’Assurance",
    //"Activités Immobilières",
    //"Activités Spécialisées, Scientifiques Et Techniques",
    //"Arts, Sports Et Activités Récréatives",
    //"Autres Activités De Services",
    //"Construction",
    //"Industrie Manufacturière",
    //"SectorGroup",
    //"Télécommunications, Programmation Informatique, Conseil, Infrastructure Informatique Et Autres Activités De Service D'Information",
    //"Transports Et Entreposage",
    "Hébergement Et Restauration",
    "Commerce",
]

const streetNames1030_FR = [
    "non renseigné",
    "Allée des Freesias",
    "Avenue Adolphe Lacomblé",
    "Avenue Albert Desenfans",
    "Avenue Albert Giraud",
    "Avenue Ambassadeur van Vollenhoven",
    "Avenue Britsiers",
    "Avenue Charbo",
    "Avenue Charles Gilisquet",
    "Avenue Chazal",
    "Avenue Clays",
    "Avenue Colonel Picquart",
    "Avenue Dailly",
    "Avenue de la Brabançonne",
    "Avenue de la Reine",
    "Avenue de la Topaze",
    "Avenue de l'Emeraude",
    "Avenue de l'Héliport",
    "Avenue de l'Opale",
    "Avenue de Mars",
    "Avenue de Roodebeek",
    "Avenue des Azalées",
    "Avenue des Capucines",
    "Avenue des Cerisiers",
    "Avenue des Clos",
    "Avenue des Glycines",
    "Avenue des Héliotropes",
    "Avenue des Jacinthes",
    "Avenue des Jardins",
    "Avenue Docteur Dejase",
    "Avenue du Cimetière",
    "Avenue du Diamant",
    "Avenue du Suffrage Universel",
    "Avenue Emile Max",
    "Avenue Emile Verhaeren",
    "Avenue Emile Zola",
    "Avenue Ernest Cambier",
    "Avenue Ernest Renan",
    "Avenue Eugène Demolder",
    "Avenue Eugène Plasky",
    "Avenue Félix Marchal",
    "Avenue Fortin",
    "Avenue Frans Courtens",
    "Avenue Général Eisenhower",
    "Avenue Georges Eekhoud",
    "Avenue Georges Rodenbach",
    "Avenue Gustave Latinis",
    "Avenue Herbert Hoover",
    "Avenue Huart Hamoir",
    "Avenue Jacques Georgin",
    "Avenue Jan Stobbaerts",
    "Avenue Jean Jaurès",
    "Avenue Léon Mahillon",
    "Avenue Louis Bertrand",
    "Avenue Maréchal Foch",
    "Avenue Maurice Maeterlinck",
    "Avenue Milcamps",
    "Avenue Monplaisir",
    "Avenue Paul Deschanel",
    "Avenue Princesse Elisabeth",
    "Avenue Raymond Foucart",
    "Avenue Rogier",
    "Avenue Sleeckx",
    "Avenue Voltaire",
    "Avenue Zénobe Gramme",
    "Boulevard Auguste Reyers",
    "Boulevard du Roi Albert II",
    "Boulevard Général Wahis",
    "Boulevard Lambermont",
    "Boulevard Léopold III",
    "Boulevard Simon Bolivar",
    "Chaussée de Haecht",
    "Chaussée de Helmet",
    "Chaussée de Louvain",
    "Cité Ouvrière de Linthout",
    "Clos des Mouettes",
    "Clos du Chemin Creux",
    "Grande rue au Bois",
    "Petite rue L'Olivier",
    "Place Colignon",
    "Place Colonel Bremer",
    "Place Dailly",
    "Place de Helmet",
    "Place de Houffalize",
    "Place de Jamblinne de Meux",
    "Place de la Patrie",
    "Place de la Reine",
    "Place des Bienfaiteurs",
    "Place des Carabiniers",
    "Place des Chasseurs Ardennais",
    "Place Eugène Verboekhoven",
    "Place Gaucheret",
    "Place Général Meiser",
    "Place Lehon",
    "Place Liedts",
    "Place Masui",
    "Place Princesse Elisabeth",
    "Place Solvay",
    "Place Stephenson",
    "Place Terdelt",
    "Place Wappers",
    "Rue Achille Detienne",
    "Rue Adolphe Marbotin",
    "Rue Aimé Smekens",
    "Rue Albert de Latour",
    "Rue Alexandre De Craene",
    "Rue Alexandre Markelbach",
    "Rue Allard",
    "Rue Anatole France",
    "Rue André Van Hasselt",
    "Rue Armand de Roo",
    "Rue Artan",
    "Rue Arthur Roland",
    "Rue Auguste Lambiotte",
    "Rue Auguste Snieders",
    "Rue Brichaut",
    "Rue Camille Simoens",
    "Rue Camille Wollès",
    "Rue Caporal Claes",
    "Rue Capronnier",
    "Rue Charles Meert",
    "Rue Charles Van Lerberghe",
    "Rue Charles Vanderstappen",
    "Rue Colonel Bourg",
    "Rue Cornet de Grez",
    "Rue Creuse",
    "Rue d'Aerschot",
    "Rue d'Anethan",
    "Rue de Beughem",
    "Rue de Brabant",
    "Rue de Cologne",
    "Rue de Genève",
    "Rue de Jérusalem",
    "Rue de la Bruyère",
    "Rue de la Chaumière",
    "Rue de la Cible",
    "Rue de la Consolation",
    "Rue de la Constitution",
    "Rue de la Fraternité",
    "Rue de la Luzerne",
    "Rue de la Marne",
    "Rue de la Poste",
    "Rue de la Ruche",
    "Rue de l'Agriculture",
    "Rue de l'Est",
    "Rue de Linthout",
    "Rue de Locht",
    "Rue de l'Orme",
    "Rue de Moerkerke",
    "Rue de Potter",
    "Rue de Quatrecht",
    "Rue de Robiano",
    "Rue des Ailes",
    "Rue des Chardons",
    "Rue des Compagnons",
    "Rue des Coteaux",
    "Rue des Mimosas",
    "Rue des Palais",
    "Rue des Pâquerettes",
    "Rue des Pavots",
    "Rue des Pensées",
    "Rue des Plantes",
    "Rue Désiré Desmet",
    "Rue Destouvelles",
    "Rue d'Hoogvorst",
    "Rue Docteur Elie Lambotte",
    "Rue du 150E Anniversaire, 24",
    "Rue du Corbeau",
    "Rue du Dahlia",
    "Rue du Foyer Schaerbeekois",
    "Rue du Noyer",
    "Rue du Pavillon",
    "Rue du Progrès",
    "Rue du Radium",
    "Rue du Saphir",
    "Rue du Tilleul",
    "Rue Dupont",
    "Rue Edouard Fiers",
    "Rue Emile Wittmann",
    "Rue Emmanuel Hiel",
    "Rue Ernest Discailles",
    "Rue Ernest Laude",
    "Rue Eugène Smits",
    "Rue Fernand Séverin",
    "Rue Floris",
    "Rue Fontaine d'Amour",
    "Rue Fraikin",
    "Rue François Bossaerts",
    "Rue François Degreef",
    "Rue François-Joseph Navez",
    "Rue Frans Binjé",
    "Rue Frédéric Pelletier",
    "Rue Gallait",
    "Rue Gaucheret",
    "Rue Geefs",
    "Rue Gendebien",
    "Rue Général Eenens",
    "Rue Général Gratry",
    "Rue Georges Garnir",
    "Rue Georges Raeymaekers",
    "Rue Godefroid Devreese",
    "Rue Godefroid Guffens",
    "Rue Goossens",
    "Rue Grégoire Leroy",
    "Rue Guido Gezelle",
    "Rue Guillaume Kennis",
    "Rue Gustave Fuss",
    "Rue Gustave Huberti",
    "Rue Hancart",
    "Rue Henri Bergé",
    "Rue Henri Chomé",
    "Rue Henri Evenepoel",
    "Rue Henri Jacobs",
    "Rue Henri Stacquet",
    "Rue Henry Villard",
    "Rue Herman",
    "Rue Herman Richir",
    "Rue Hubert Krains",
    "Rue Iwan Gilkin",
    "Rue Jacques Jansen",
    "Rue Jacques Rayé",
    "Rue James Watt",
    "Rue Jan Blockx",
    "Rue Jenatzy",
    "Rue Jolly",
    "Rue Josaphat",
    "Rue Joseph Brand",
    "Rue Joseph Coosemans",
    "Rue Joseph Jacquet",
    "Rue Joseph Van Camp",
    "Rue Joseph Wauters",
    "Rue Josse Impens",
    "Rue Jules Destrée",
    "Rue Jules Lebrun",
    "Rue Kessels",
    "Rue Knapen",
    "Rue Lefrancq",
    "Rue Léon Frédéric",
    "Rue Léon Mignon",
    "Rue Léopold Courouble",
    "Rue Liedts",
    "Rue Linné",
    "Rue L'Olivier",
    "Rue Louis Scutenaire",
    "Rue Louis Socquet",
    "Rue Marcel Mariën",
    "Rue Marguerite Van de Wiele",
    "Rue Massaux",
    "Rue Masui",
    "Rue Maurice des Ombiaux",
    "Rue Max Roos",
    "Rue Metsys",
    "Rue Monrose",
    "Rue Nestor De Tière",
    "Rue Nicolas Defrêcheux",
    "Rue Paul Devigne",
    "Rue Paul Hymans",
    "Rue Paul Leduc",
    "Rue Philomène",
    "Rue Pierre Theunis",
    "Rue Portaels",
    "Rue Potagère",
    "Rue Quinaux",
    "Rue Rasson",
    "Rue Renkin",
    "Rue Richard Vandevelde",
    "Rue Roelandts",
    "Rue Rogier",
    "Rue Royale",
    "Rue Royale-Sainte-Marie",
    "Rue Rubens",
    "Rue Sander Pierron",
    "Rue Seutin",
    "Rue Stephenson",
    "Rue Stijn Streuvels",
    "Rue Teniers",
    "Rue Théo Coopman",
    "Rue Théodore Roosevelt",
    "Rue Thiéfry",
    "Rue Thomas Vinçotte",
    "Rue Van Droogenbroeck",
    "Rue Van Dyck",
    "Rue Van Hammée",
    "Rue Van Hoorde",
    "Rue Van Hove",
    "Rue Van Oost",
    "Rue Van Schoor",
    "Rue Van Ysendyck",
    "Rue Vandenbussche",
    "Rue Vanderlinden",
    "Rue Vandermeersch",
    "Rue Vandeweyer",
    "Rue Verbist",
    "Rue Verboeckhaven",
    "Rue Vergote",
    "Rue Verhas",
    "Rue Verte",
    "Rue Verwée",
    "Rue Victor Hugo",
    "Rue Victor Lefèvre",
    "Rue Victor Oudart",
    "Rue Victor Vanderhoeft",
    "Rue Vifquin",
    "Rue Vogler",
    "Rue Vonck",
    "Rue Vondel",
    "Rue Waelhem",
    "Rue Willem Kuhnen",
    "Rue William Degouve de Nuncques",
    "Square Apollo",
    "Square Emile Duployé",
    "Square Eugène Plasky",
    "Square François Riga",
    "Square Vergote",
]

const Quartier1030 = [
    "Dehors1030",
    "Helmet-Hamoir",
    "Terdelt-Fleur",
    "Jardin",
    "Reyers",
    "Cerisiers",
    "Linthout",
    "Plasky",
    "Bienfaiteurs",
    "Coteaux-Josaphat",
    "Palais-Reine",
    "Nord",
    "Colignon",
    "Parc Josaphat",
]


// Función para poblar el datalist
function populateDatalist(listId, dataArray) {
    const datalist = document.getElementById(listId);

    // Asegúrate de que el datalist exista
    if (datalist) {
        // Itera sobre el array de datos
        dataArray.forEach(item => {
            // Crea un nuevo elemento <option>
            const option = document.createElement('option');

            // Asigna el valor del array al atributo 'value' de la opción
            option.value = item;

            // Agrega la opción al datalist
            datalist.appendChild(option);
        });
    } else {
        console.error(`Datalist con ID "${listId}" no encontrado.`);
    }
}


// BCE
// datalist_TypeEntity
document.addEventListener('DOMContentLoaded', (event) => {
    // Llama a la función para poblar el datalist 
    populateDatalist('datalist_TypeEntity', BCE_TypeEntity);
});

// datalist_TypeEnterprise
document.addEventListener('DOMContentLoaded', (event) => {
    // Llama a la función para poblar el datalist 
    populateDatalist('datalist_TypeEnterprise', BCE_TypeEnterprise);
});

// datalist_JuridicalForm
document.addEventListener('DOMContentLoaded', (event) => {
    // Llama a la función para poblar el datalist 
    populateDatalist('datalist_JuridicalForm', BCE_JuridicalForm);
});

// datalist_SecEconomique
document.addEventListener('DOMContentLoaded', (event) => {
    // Llama a la función para poblar el datalist 
    populateDatalist('datalist_SecEconomique', BCE_SecEconomique);
});

// datalist_StreetFR
document.addEventListener('DOMContentLoaded', (event) => {
    // Llama a la función para poblar el datalist 
    populateDatalist('datalist_StreetFR', streetNames1030_FR);
});

// datalist_Quartier
document.addEventListener('DOMContentLoaded', (event) => {
    // Llama a la función para poblar el datalist 
    populateDatalist('datalist_Quartier', Quartier1030);
});
